sudo: false
language: node_js
node_js:
- '6'
- '5'
- '4'
cache:
  directories:
  - node_modules
  - packages/paeckchen-core/node_modules
  - packages/paeckchen-cli/node_modules

before_script: 'npm run bootstrap; npm run linter'
script: 'npm run coverage'
after_script: "./node_modules/.bin/lcov-result-merger 'packages/*/coverage/lcov.info' | ./node_modules/.bin/coveralls"
