sudo: false
language: node_js
node_js:
- '6'
- '5'
- '4'
cache:
  directories:
  - node_modules

before_script: 'npm run linter'
script: 'npm run coverage'
after_script: 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
