environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '5'
    - nodejs_version: '4'
cache:
  - node_modules
  - packages\paeckchen-core\node_modules
  - packages\paeckchen-cli\node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
matrix:
  fast_finish: true
version: '{build}'
shallow_clone: true
clone_depth: 1
build: off
deploy: off
before_test:
  - npm install
  - npm run bootstrap
test_script:
  - npm run test
