environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '5'
    - nodejs_version: '4'
cache:
  - node_modules
  - packages\paeckchen-core\node_modules
  - packages\paeckchen-cli\node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
  - npm install
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
before_test:
  - npm run bootstrap
  - npm run linter
test_script:
  - npm run coverage
after_test:
  - .\node_modules\.bin\lcov-result-merger 'packages/*/coverage/lcov.info' | .\node_modules\.bin\coveralls
